# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y68Ul9jAfIG7P8PVS3ly2fOzZ3sIVPf7
"""

!pip install scapy

from google.colab import files
uploaded = files.upload()

from scapy.all import rdpcap
from collections import Counter

# Load the pcap file
packets = rdpcap("http.cap")

print("Total packets:", len(packets))

protocol_counter = Counter()
ip_counter = Counter()

for packet in packets:
    if packet.haslayer("IP"):
        ip_counter[packet["IP"].src] += 1

    if packet.haslayer("TCP"):
        protocol_counter["TCP"] += 1
    elif packet.haslayer("UDP"):
        protocol_counter["UDP"] += 1
    elif packet.haslayer("ICMP"):
        protocol_counter["ICMP"] += 1

print("\nProtocol counts:")
for proto, count in protocol_counter.items():
    print(proto, count)

print("\nMost common source IP:")
print(ip_counter.most_common(1))

from scapy.all import rdpcap
from collections import Counter
from google.colab import files

# Load the pcap file
packets = rdpcap("http.cap")

# Analyze protocols and IPs
protocol_counter = Counter()
ip_counter = Counter()

for packet in packets:
    if packet.haslayer("IP"):
        ip_counter[packet["IP"].src] += 1

    if packet.haslayer("TCP"):
        protocol_counter["TCP"] += 1
    elif packet.haslayer("UDP"):
        protocol_counter["UDP"] += 1
    elif packet.haslayer("ICMP"):
        protocol_counter["ICMP"] += 1

# Save results to a text file
with open("analysis_result.txt", "w") as f:
    f.write(f"Total packets: {len(packets)}\n\n")

    f.write("Protocol counts:\n")
    for proto, count in protocol_counter.items():
        f.write(f"{proto}: {count}\n")

    f.write("\nMost common source IP:\n")
    f.write(str(ip_counter.most_common(1)))

print("Results saved as analysis_result.txt")

# Download the file
files.download("analysis_result.txt")

from google.colab import files
files.download("analysis_result.txt")